### ISSUE TITLE
Feature TODO List

### ISSUE THREAD

**Issue by superckl** [superckl/BiomeTweaker#67]
All features on a per-biome basis. Many may not work with other mod features due to lack of event calls.
- ~~Disable map gens (Cave, mineshaft, nether_bridge, etc.)~~ (No biome info given)
- [x] Set max spawn pack size for entities (per entity or global) (#65)
- [x] Disable bonemeal use
- [x] Change sky color (#58)
- [x] Port `remove late block assignments` config option to 1.8 and 1.8.8 (#70)
- [x] Actual filler block metadata (#75)
- [x] Ocean top and filler block metadata

Other ideas:
- [ ] Disable sapling growth
- ~~Break speed multiplier (per block or global)~~ (No interest/too weird)
- ~~Break speed override (per block or global)~~ (No interest/too weird)
- ~~Healing multiplier (per entity or global)~~ (No interest/too weird)
- ~~Healing override (per entity or global)~~ (No interest/too weird)
- ~~Disable ender teleports (to and from)~~ (No interest/too weird)
- ~~Disable bed use~~ (No interest/too weird)
- ~~Disable hoe use~~ (No interest/too weird)

List subject to change. Please suggest more features or tell me why an existing one shouldn't be implemented.

**Comment by MrBloodowrth** [comment]
Maybe I'm not seeing it, but for Mob spawns a "Max per chunk" would be awesome. (1.7.10 please and thank you)

**Comment by MechWarrior99** [comment]
The ability to have grass and foliage color variation on a per biome bases.
Options I would like to see with this feature: 
    \* set the chance for the effect to occur in a biome(Can occur multiple times in one biome)
    \* set the rough size of the area that would be effected(In blocks)
    \* set which biomes are effected
    \* set color of effect

Example of how a script could look. I am still vary much learning how BT works and the different functions it has. There maybe a much better way to do it then 'set', but I hope this gives you a better idea of how it would work

```
#Specify id
myBiome = forBiomes(1)

#Set the color of the alternate grass
myBiome.set("grassColorVariant"  12308294)

#Set the size of the area that the alternate grass color would effect
myBiome.set("grassColorVarientSize" 15)

#Set the chance of that alternate grass color to be used
myBiome.set("grassColorVariantChance" 5)
```

And [here](http://puu.sh/qvTnQ/0a89d465a6.jpg) is a swamp biome for reference sake.

**Comment by StealthyExpertX** [comment]
Feature request add a random Biome command witch every block by block biome would be random based on an array the user would create in his' or her script.

**Comment by gdarai** [comment]
Feature request to be able to limit the tweak only to a particuar dimension
